src/App.module.scss
src/components/Sidebar/Sidebar.module.scss
src/pages/AdminTweetListPage/AdminTweetListPage.module.scss
src/pages/AdminUserListPage/AdminUserListPage.module.scss
src/pages/SettingPage/SettingPage.module.scss

將外框的長跟寬的設定移除，撤銷回feature/e時合併回去的style

style: revert to the style at feature/e

---

src/App.jsx

fix: fix the wrong import url of userData

---

.env
package-lock.json
package.json

feat: add the setting of deploy

---

src/App.jsx

新增首頁位置到BrowserRouter上，這樣才會導向我們希望的位置 https://ibuki0102.github.io/simple-twitter 上

feat: add basename to BrowserRouter

---

src/App.jsx
src/index.js

將BrowserRouter 包在index.js使用，而非app.jsx

feat: use BrowserRouter at index.js instead

---

package-lock.json
package.json
src/App.jsx
src/api/auth.js
src/components/AuthInput/AuthInput.jsx
src/pages/LoginPage/LoginPage.jsx

新增 axios，嘗試串接前台登入的 API。LoginPage 加入 useState 管理帳號及密碼，AuthInput 元件加入 onChange 的 props

feat: add axios, props and useState

---

package-lock.json
package.json
src/api/auth.js
src/components/AuthInput/AuthInput.jsx
src/components/AuthInput/AuthInput.module.scss
src/pages/AdminLoginPage/AdminLoginPage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.module.scss
src/pages/RegistPage/RegistPage.jsx

登入/註冊/後台登入頁面現在可以透過連結切換，註冊頁面現在已經可以互動，帳號/使用者名稱會隨著使用者輸入而顯示字數，防止使用者送出有欄位未填的表單，送出後如果註冊失敗會在對應的欄位顯示錯誤訊息。

feat: login/regist/abmin page now linked, regist page now interactive

---

src/api/auth.js
src/components/PopularUser/PopularUser.jsx
src/components/PopularUser/PopularUser.module.scss
src/components/UserPostList/UserPostList.jsx
src/pages/LoginPage/LoginPage.jsx

feat: setting page and userProfile page connected api data

---

src/components/Sidebar/Sidebar.jsx
src/components/Sidebar/Sidebar.module.scss
src/components/TweetList/TweetList.jsx
src/components/TweetList/TweetList.module.scss
src/components/TweetModal/TweetModal.jsx
src/pages/MainPage/MainPage.jsx
src/pages/MainPage/MainPage.module.scss
src/pages/SettingPage/SettingPage.module.scss
src/pages/UserTweetPage/UserTweetPage.jsx

左側的導覽列現在可以切換畫面了，也有對應的acitve樣式，然後推文的modal現在可以打開或關閉(還沒辦法推文)

feat: sidebar interactive and have active style

---

src/components/Sidebar/Sidebar.jsx
src/pages/UserTweetPage/UserTweetPage.jsx

修復了sidebar從首頁沒辦法到個人資訊頁的問題，有確認後台的sidebar也可以正常轉址

fix: now sidebar works ok

---

src/api/auth.js
src/api/mainPageTweets.js
src/components/AuthInput/AuthInput.jsx
src/components/InputTextArea/InputTextArea.jsx
src/components/TweetList/TweetList.jsx
src/components/TweetModal/TweetModal.jsx
src/components/TweetModal/TweetModal.module.scss
src/pages/LoginPage/LoginPage.jsx
src/pages/MainPage/MainPage.jsx
src/pages/RegistPage/RegistPage.jsx
src/pages/SettingPage/SettingPage.jsx

新增推文的api，目前可以推文了，然後登入頁會顯示錯誤訊息了，還有串接正確資料(email, 頭像, 背景圖片)

feat: add tweet api

---

src/api/userFollowPage.js
src/components/UserFollowItem/UserFollowItem.jsx
src/components/UserFollowItem/UserFollowItem.module.scss
src/components/UserFollowList/UserFollowList.jsx
src/components/UserFollowList/UserFollowList.module.scss
src/pages/UserFollowPage/UserFollowPage.jsx

串接 UserFollowPage (主頁的 '追隨者' 以及 '正在追隨') 的 API

feat: connect API in UserFollowPage

---

src/components/TweetItem/TweetItem.jsx
src/components/TweetItemCollection/TweetItemCollection.jsx
src/components/TweetList/TweetList.jsx
src/components/UserPostList/UserPostList.jsx
src/pages/MainPage/MainPage.jsx

feat: delete props 'page'

---

src/api/auth.js
src/api/follow.js
src/api/mainPageTweets.js
src/components/PopularUser/PopularUser.jsx
src/components/PopularUser/PopularUser.module.scss
src/components/PopularUserList/PopularUserList.jsx
src/components/PopularUserList/PopularUserList.module.scss
src/pages/MainPage/MainPage.jsx

推薦追隨目前套用了api回傳的資料，且可以點擊追隨以及取消追隨

feat: popular list now have api return data

---

src/App.jsx
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/UserFollowList/UserFollowList.jsx
src/components/UserPostList/UserPostList.jsx
src/contexts/PageContext.js
src/pages/UserFollowPage/UserFollowPage.jsx
src/pages/UserTweetPage/UserTweetPage.jsx

feat: add context to manage the current page

---

src/App.jsx
src/api/getOneTweet.js
src/components/ReplyModal/ReplyModal.jsx
src/components/Sidebar/Sidebar.jsx
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/TweetList/TweetList.jsx
src/contexts/ReplyContext.js
src/pages/MainPage/MainPage.jsx

feat: reply icon now show reply modal

---

src/App.jsx
src/api/replyTweet.js
src/components/ReplyItem/ReplyItem.jsx
src/components/ReplyItemCollection/ReplyItemCollection.jsx
src/components/ReplyList/ReplyList.jsx
src/components/ReplyList/ReplyList.module.scss
src/components/ReplyModal/ReplyModal.module.scss
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/TweetList/TweetList.jsx
src/contexts/ReplyTweetContext.js
src/pages/MainPage/MainPage.jsx

新增回覆頁，現在從首頁點推文會進到回覆頁面，回覆頁面內可以回覆

feat: add reply page, can reply in reply page

---

src/api/like.js
src/components/ReplyList/ReplyList.jsx
src/components/ReplyList/ReplyList.module.scss
src/pages/ReplyListPage/ReplyListPage.jsx

feat: connect LikeTweet and unLikeTweet in ReplyList

---

src/App.jsx
src/components/ReplyList/ReplyList.jsx
src/contexts/DataContext.js

把所有的Context統一放到DataContext裡，這樣App.jsx就只要放一個Context.Provider

refactor: use DataContext.Provider instead of each provider in app.jsx

---

src/api/getOneTweet.js
src/api/like.js
src/components/ReplyItem/ReplyItem.jsx
src/components/ReplyItem/ReplyItem.module.scss
src/components/ReplyItemCollection/ReplyItemCollection.jsx
src/components/ReplyList/ReplyList.jsx
src/components/ReplyModal/ReplyModal.jsx
src/components/UserPostList/UserPostList.jsx
src/components/UserPostList/UserPostList.module.scss
src/pages/ReplyListPage/ReplyListPage.jsx
src/pages/UserTweetPage/UserTweetPage.jsx

個人資訊頁的下方現在可以切換了，修了回覆頁面上的問題，目前個人資訊頁下方的回覆仍然有已刪除的推文待修正

feat&fix: UserTweetPage now complete, fix reply page.

---

src/components/OtherUserPostList/OtherUserPostList.jsx
src/components/OtherUserPostList/OtherUserPostList.module.scss
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/TweetItemCollection/TweetItemCollection.jsx
src/components/TweetList/TweetList.jsx
src/components/UserPostList/UserPostList.jsx
src/contexts/DataContext.js
src/contexts/UserContext.js
src/pages/MainPage/MainPage.jsx
src/pages/OtherTweetPage/OtherTweetPage.jsx
src/pages/UserTweetPage/UserTweetPage.jsx

增加 context 管理點擊頭像 id，串接他人資料頁面 (OtherTweetPage) 的 API

feat: connect API of OtherTweetPage

---

src/components/OtherUserPostList/OtherUserPostList.jsx
src/components/TweetItem/TweetItem.jsx
src/components/UserFollowList/UserFollowList.jsx
src/components/UserPostList/UserPostList.jsx
src/components/UserPostList/UserPostList.module.scss
src/pages/UserTweetPage/UserTweetPage.jsx

feat: add the return function of button

---

src/api/setting.js
src/components/PopularUser/PopularUser.module.scss
src/components/ProfileEditModal/ProfileEditModal.jsx
src/components/ReplyItem/ReplyItem.module.scss
src/components/ReplyList/ReplyList.jsx
src/components/ReplyList/ReplyList.module.scss
src/components/ReplyModal/ReplyModal.jsx
src/components/ReplyModal/ReplyModal.module.scss
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/TweetList/TweetList.module.scss

在編輯個人資料的modal按下x後按儲存後，會將使用者的cover資料清空，頁面會顯示預設的cover

fix: user now click x and save will works

---

src/components/AdminTweetListItem/AdminTweetListItem.jsx
src/components/AdminTweetListItem/AdminTweetListItem.module.scss
src/components/Sidebar/Sidebar.jsx
src/contexts/DataContext.js
src/contexts/TweetModalContext.js
src/pages/ReplyListPage/ReplyListPage.jsx

style: fix the avatar size at admin page

---

src/components/ReplyModal/ReplyModal.jsx
src/components/ReplyModal/ReplyModal.module.scss
src/components/Sidebar/Sidebar.jsx
src/components/TweetItem/TweetItem.jsx
src/components/TweetItem/TweetItem.module.scss
src/components/TweetItemCollection/TweetItemCollection.jsx
src/components/TweetList/TweetList.jsx
src/components/TweetModal/TweetModal.jsx
src/components/TweetModal/TweetModal.module.scss
src/contexts/DataContext.js
src/pages/MainPage/MainPage.jsx
src/pages/ReplyListPage/ReplyListPage.jsx

1. 原本在首頁回復貼文的話貼文的回復數量不會自動更新，現在會自動更新了
2. 在回覆頁面點sidebar的按紐會回到首頁並顯示推文modal
3. 首頁的推文可點擊範圍要包含下面的icon

fix&style: reply at main page now auto refresh data

---

src/api/auth.js
src/components/OtherUserPostList/OtherUserPostList.jsx
src/components/PopularUser/PopularUser.jsx
src/components/PopularUserList/PopularUserList.jsx
src/components/PopularUserList/PopularUserList.module.scss
src/components/ProfileEditModal/ProfileEditModal.jsx
src/components/ProfileEditModal/ProfileEditModal.module.scss
src/components/Sidebar/Sidebar.jsx
src/components/TweetItemCollection/TweetItemCollection.jsx
src/pages/AdminLoginPage/AdminLoginPage.jsx
src/pages/Homepage/Homepage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/OtherTweetPage/OtherTweetPage.jsx

阻止前台使用者進入後台，後台使用者進入前台，使用者可以在他人的個人資訊頁點擊追隨/取消追隨

feat: prevent user to enter admin page

---

src/pages/AdminLoginPage/AdminLoginPage.jsx
src/pages/Homepage/Homepage.jsx

解決部屬後仍可以透過轉址從後台進入到前台畫面的問題，目前部屬上去的版本已經解決了

fix: fix admin can enter main page bug

---

src/App.module.scss
src/components/LikeItem/LikeItem.module.scss
src/components/OtherUserPostList/OtherUserPostList.module.scss
src/components/ProfileEditModal/ProfileEditModal.jsx
src/components/ReplyItem/ReplyItem.module.scss
src/components/ReplyList/ReplyList.module.scss
src/components/ReplyModal/ReplyModal.module.scss
src/components/Sidebar/Sidebar.module.scss
src/components/TweetItem/TweetItem.module.scss
src/components/TweetList/TweetList.module.scss
src/components/TweetModal/TweetModal.module.scss
src/components/UserFollowItem/UserFollowItem.module.scss
src/components/UserFollowList/UserFollowList.module.scss
src/components/UserPostList/UserPostList.module.scss
src/pages/AdminTweetListPage/AdminTweetListPage.module.scss
src/pages/AdminUserListPage/AdminUserListPage.module.scss
src/pages/MainPage/MainPage.module.scss
src/pages/OtherTweetPage/OtherTweetPage.module.scss
src/pages/OtherUserFollowPage/OtherUserFollowPage.module.scss
src/pages/ReplyListPage/ReplyListPage.module.scss
src/pages/SettingPage/SettingPage.module.scss
src/pages/UserFollowPage/UserFollowPage.module.scss
src/pages/UserTweetPage/UserTweetPage.module.scss

重新調整了所有頁面的細節，包含中間區塊的寬度以及排版的一致性

style: re-adjust all page style

---

src/App.jsx
src/api/mainPageTweets.js
src/components/AuthInput/AuthInput.jsx
src/components/Notification/Notification.jsx
src/components/Notification/Notification.module.scss
src/components/TweetList/TweetList.jsx
src/components/TweetModal/TweetModal.jsx
src/contexts/DataContext.js
src/contexts/NotiContext.js
src/pages/AdminLoginPage/AdminLoginPage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.module.scss
src/pages/MainPage/MainPage.jsx
src/pages/RegistPage/RegistPage.jsx

feat: add notification of login/regist/tweet

---

src/components/PopularUserList/PopularUserList.jsx

fix: popular list now won't show the current user

---

src/components/Sidebar/Sidebar.jsx
src/components/UserFollowItem/UserFollowItem.jsx
src/components/UserFollowItem/UserFollowItem.module.scss

feat: revise follow button in UserFollowItem

---

src/components/AuthInput/AuthInput.jsx
src/components/PopularUser/PopularUser.jsx
src/components/PopularUserList/PopularUserList.jsx
src/components/ProfileEditModal/ProfileEditModal.jsx
src/components/ReplyList/ReplyList.jsx
src/components/ReplyList/ReplyList.module.scss
src/components/UserFollowItem/UserFollowItem.jsx
src/components/UserPostList/UserPostList.jsx
src/pages/MainPage/MainPage.jsx
src/pages/OtherUserFollowPage/OtherUserFollowPage.jsx
src/pages/SettingPage/SettingPage.jsx
src/pages/UserFollowPage/UserFollowPage.jsx

追隨頁面的按鈕現在有功能了
將沒有用到的變數都移除了
回覆頁面的大頭貼現在可以點了
帳戶設定頁如果回傳設定失敗，輸入欄位的值不會改變

feat&refactor: add button func in follow page, remove unused variable

---

src/components/PopularUser/PopularUser.jsx
src/components/PopularUser/PopularUser.module.scss

feat: change the length of name in PopularUser

---

src/components/ProfileEditModal/ProfileEditModal.jsx
src/components/ReplyItem/ReplyItem.jsx
src/components/ReplyModal/ReplyModal.jsx
src/components/TweetModal/TweetModal.jsx
src/pages/Homepage/Homepage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/SettingPage/SettingPage.jsx

修改了編輯個人資料的背景後，再點出modal結果什麼都沒改後按儲存，背景圖片會變成預設的bug
修正了某些通知的動畫不會彈出的問題

fix: fix the bug of editProfileModal, adjust the noti animation

---

src/components/PopularUser/PopularUser.module.scss
src/components/PopularUserList/PopularUserList.module.scss
src/components/ReplyList/ReplyList.module.scss

style: add scrollbar to popular list when overflow

---

src/components/ReplyList/ReplyList.jsx
src/components/ReplyList/ReplyList.module.scss

feat: change like icon

---

src/components/TweetItem/TweetItem.jsx

fix: fix the datetime display disapear at profile page

---

src/pages/Homepage/Homepage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/RegistPage/RegistPage.jsx

feat: add comment to login/regist/homepage

---

src/pages/MainPage/MainPage.jsx
src/pages/UserTweetPage/UserTweetPage.jsx

feat: add comment

---

src/components/ProfileEditModal/ProfileEditModal.jsx

feat: add comment to editProfileModal
